### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'start_stop_order'

### ISSUE THREAD

**Issue by simbs** [elastic/apm-agent-python#1147]
# Error
We started seeing this traceback via Sentry coming from the elasticapm agent with the Django integration after upgrading from 6.1.3 to 6.2.0:

```
AttributeError: 'Config' object has no attribute 'start_stop_order'
  File "elasticapm/instrumentation/packages/dbapi2.py", line 276, in call_if_sampling
    return self.call(module, method, wrapped, instance, args, kwargs)
  File "elasticapm/instrumentation/packages/psycopg2.py", line 104, in call
    return PGConnectionProxy(wrapped(*args, **kwargs), destination_info=destination_info)
  File "elasticapm/traces.py", line 709, in __exit__
    span = transaction.end_span(self.skip_frames, duration=self.duration, outcome=outcome)
  File "elasticapm/traces.py", line 293, in end_span
    span.end(skip_frames=skip_frames, duration=duration)
  File "elasticapm/traces.py", line 484, in end
    tracer.queue_func(SPAN, self.to_dict())
  File "elasticapm/base.py", line 275, in queue
    self.start_threads()
  File "elasticapm/base.py", line 220, in start_threads
    for manager_type, manager in sorted(
  File "elasticapm/base.py", line 221, in <lambda>
    self._thread_managers.items(), key=lambda item: item[1].start_stop_order
  File "elasticapm/conf/__init__.py", line 709, in __getattr__
    return getattr(self._config, item)
```

# Environment

OS: Linux
Python version: 3.8.9
Framework and version [e.g. Django 2.1]: Django 3.1.10
APM Server version: 7.6
Agent version: 6.2.0

# Additional context

I think the bug was introduced in https://github.com/elastic/apm-agent-python/pull/1139/files.

The change sorts `self._thread_managers.items()` by the `start_stop_order` of each dict item.
`self._thread_managers['config']` is an instance of [`VersionedConfig`](https://github.com/elastic/apm-agent-python/blob/master/elasticapm/conf/__init__.py#L636), which inherits [`ThreadManager`](https://github.com/elastic/apm-agent-python/blob/c5fe64662f971f26deb200b4619860c363b3e483/elasticapm/utils/threading.py#L98) where this attribute is set. But the `__getattr__` method of `VersionedConfig` [is overriden](https://github.com/elastic/apm-agent-python/blob/master/elasticapm/conf/__init__.py#L708) to instead fetch the item from `VersionedConfig._config`, which is a [`Config`](https://github.com/elastic/apm-agent-python/blob/master/elasticapm/conf/__init__.py#L508) object and doesn't have the attribute `start_stop_order`.

**Comment by beniwohli** [comment]
Hey @simbs, great catch and great analysis of the problem! I'll get a fix shipped ASAP

**Comment by beniwohli** [comment]
The fix is in #1149. It turned out to be slightly more complicated. The bug wasn't in `VersionedConfig.__getattr__`, but in the fact that we forgot to add `start_stop_order` to `VersionedConfig.__slots__`. We exclude attributes in `__slots__` from being proxied to the underlying `Config` object in `VersionedConfig.__setattr__`.

So what happened was that when `ThreadManager.__init__()` sets the `start_stop_order` attribute, we mistakenly proxy it to the initial `Config` object. As long as that `Config` object isn't switched out, everything looks like it works. Things only break once the configuration is updated for the first time and the old `Config` object is replaced with a new one that doesn't have the `start_stop_order` attribute set.

The fix is pretty trivial (add `start_stop_order` to `__slots__`), but we might need to look into making this a bit less brittle for the next time we add an attribute to `ThreadManager`...

**Comment by beniwohli** [comment]
@simbs version 6.2.2 of the agent should fix this issue! Thanks again for reporting it!
