### ISSUE TITLE
AttributeError with kafka-python integration in 6.10.0

### ISSUE THREAD

**Issue by ccorbacho** [elastic/apm-agent-python#1578]
**Describe the bug**:

After upgrading the agent to 6.10.0, we immediately started seeing AttributeError failues in the ElasticAPM code when calling through to our kafka-python code paths (we've had to rollback to 6.9 because of this).

**To Reproduce**

Try to send a message using the KafkaProducer class in kafka-python.

Traceback:

```python
AttributeError: 'NoneType' object has no attribute 'id'
[...]
  File "elasticapm/instrumentation/packages/kafka.py", line 94, in call_if_sampling
    return self.call(module, method, wrapped, instance, args, kwargs)
  File "elasticapm/instrumentation/packages/kafka.py", line 106, in call
    return self._trace_send(instance, wrapped, destination_info=destination_info, *args, **kwargs)
  File "elasticapm/instrumentation/packages/kafka.py", line 71, in _trace_send
    tp = transaction.trace_parent.copy_from(span_id=span.id)
```

I have had to remove proprietary code from the stack trace. However, the two snipped lines of code before it hits the elasticapm code paths is basically just doing:

```python
from kafka import KafkaProducer
producer = KafkaProducer(**kafka_config)  # where kafka_config is a dict of config options.
producer.send(topic, message).get()
```

**Environment (please complete the following information)**
- OS: Linux
- Python version: 3.9.6-slim-bullseye (Docker container)
- Framework and version [e.g. Django 2.1]: Django 3.2.13, kafka-python 2.0.2
- Agent version: 6.10.0

**Comment by beniwohli** [comment]
Hi @ccorbacho. Thanks for the detailed bug report! Judging from the stack trace and the code, it looks like this error could be triggered if a transaction is unsampled. Just to confirm, have you set up sampling by configuring [`transaction_sample_rate`](https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-transaction-sample-rate)?

The fix should be relatively quick, I'll open a PR soon.

**Comment by ccorbacho** [comment]
@beniwohli Yes, we set the transaction_sample_rate to 0.1 for this project.
